language: ruby
env: MSF_SPOTCHECK_RECENT=1
before_install:
  - rake --version
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap-dev
  # don't generate docs for installed gems since no one will read them
  - 'echo ''gem --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
  - ./tools/msftidy.rb
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake parallel:create
  - bundle exec rake parallel:prepare > /dev/null 2>&1
bundler_args: --without documentation profiling
script: "bundle exec rake parallel:spec[8]"

rvm:
  #- '1.8.7'
  - '1.9.3'

notifications:
  irc: "irc.freenode.org#msfnotify"

git:
  depth: 5
