language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap-dev
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake parallel:create
  - bundle exec rake parallel:prepare > /dev/null 2>&1
bundler_args: --without documentation profiling
env:
  - SPEC_OPTS="--tag ui"
  - SPEC_OPTS="--tag ~ui"
git:
  depth: 1
notifications:
  irc: "irc.freenode.org#msfnotify"
rvm:
  - '1.9.3'
script: "bundle exec rake parallel:spec"
