build_script:
  - ps: gem install bundler
  - ps: bundle install --without pcap

before_test:
  - ps: cp config/database.yml.appveyor config/database.yml
  - ps: bundle exec rake --version
  - ps: bundle exec db:create
  - ps: bundle exec db:migrate

environment:
  matrix:
    - RAKE_TASK: cucumber
    - RAKE_TASK: cucumber:boot
    - RAKE_TASK: spec
      SPEC_OPTS: "--tag content"
    - RAKE_TASK: spec
      SPEC_OPTS: "--tag ~content"

services:
  - postgresql

test_script:
  - ps: bundle exec rake $RAKE_TASK