build_script:
  - gem install bundler
  - bundle install --without pcap

before_test:
  - cp config/database.yml.appveyor config/database.yml
  - bundle exec rake --version
  - bundle exec db:create
  - bundle exec db:migrate

environment:
  matrix:
    - RAKE_TASK: cucumber
    - RAKE_TASK: cucumber:boot
    - RAKE_TASK: spec
      SPEC_OPTS: "--tag content"
    - RAKE_TASK: spec
      SPEC_OPTS: "--tag ~content"

services:
  - postgresql

test_script:
  - bundle exec rake $RAKE_TASK