#!/usr/bin/env ruby
# -*- coding: binary -*-

#
# Standard Library
#

require 'pathname'

real_pathname = Pathname.new(__FILE__).realpath
root = real_pathname.parent
lib_real_pathname = root.join('lib')
lib_real_path = lib_real_pathname.to_path

unless $LOAD_PATH.include? lib_real_path
  $LOAD_PATH.unshift(lib_real_path)
end

#
# Project
#

# sets up Bundler environment
require 'msfenv'

require 'metasploit/framework'

command_line_interface = Metasploit::Framework::CommandLineInterface::Command::CommandLineInterface.new(words: ARGV)
command_line_interface.run
